template:
  path: nuxeo-extent-stats.yaml
  type: file
parameters:
  SourceVersion: main
  EcrRepo: nuxeo-extent-stats
  S3Bucket: nuxeo-extent-stats
  EcsClusterName: nuxeo
  Campuses: ["UCB","UCD","UCI","UCLA","UCM","UCOP","UCR","UCSC","UCSD","UCSF"]
  MetadataUri: "s3://nuxeo-extent-stats/metadata"
  ReportsUri: "s3://nuxeo-extent-stats/reports"
  TempDir: "/nuxeo-extent-stats/tmp"
  NuxeoApiToken: !environment_variable NUXEO_API_TOKEN
  NuxeoApiUrl: "https://nuxeo.cdlib.org/nuxeo/site/api/v1"
  NuxeoDbQueryToken: !environment_variable NUXEO_DBQUERY_TOKEN
  NuxeoDbQueryUrl: "https://nuxeo.cdlib.org/cdl_dbquery"
